export type ApplicationStatus =
  | "bekliyor"
  | "degerleniyor"
  | "onaylandi"
  | "reddedildi";

export type Application = {
  id: string;
  adSoyad: string;
  telefon: string;
  eposta: string;
  ikametSehir: string;
  mulkTipi: "daire" | "mustakil" | "dukkan";
  sehir: string;
  ilce: string;
  mahalle: string;
  metrekare: number;
  odaSayisi: string;
  beklenenKira: number;
  sozlesmeSuresi: number;
  esyaliMi: boolean;
  status: ApplicationStatus;
  basvuruTarihi: string; // ISO
  notlar?: string;
  atayan?: string;
};

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "KG-2026-A8F3K",
    adSoyad: "Mehmet Kara",
    telefon: "0545 222 11 33",
    eposta: "mehmet.kara@example.com",
    ikametSehir: "Kahramanmaraş",
    mulkTipi: "daire",
    sehir: "Kahramanmaraş",
    ilce: "Onikişubat",
    mahalle: "İsmetpaşa",
    metrekare: 110,
    odaSayisi: "2+1",
    beklenenKira: 18000,
    sozlesmeSuresi: 12,
    esyaliMi: false,
    status: "bekliyor",
    basvuruTarihi: "2026-05-17T08:14:00Z",
    notlar: "Hızlı dönüş istiyor, emekli.",
  },
  {
    id: "KG-2026-B2L9P",
    adSoyad: "Gülay Demir",
    telefon: "0532 887 65 12",
    eposta: "gulay.demir@example.com",
    ikametSehir: "Yurt Dışında Yaşıyorum",
    mulkTipi: "daire",
    sehir: "Antalya",
    ilce: "Alanya",
    mahalle: "Mahmutlar",
    metrekare: 85,
    odaSayisi: "1+1",
    beklenenKira: 22000,
    sozlesmeSuresi: 24,
    esyaliMi: true,
    status: "degerleniyor",
    basvuruTarihi: "2026-05-16T19:42:00Z",
    notlar: "Almanya'dan, gurbetçi paketi gerekli.",
    atayan: "Selin Kara",
  },
  {
    id: "KG-2026-C5M2X",
    adSoyad: "Ayşe Demirci",
    telefon: "0506 122 33 44",
    eposta: "ayse.demirci@example.com",
    ikametSehir: "İstanbul",
    mulkTipi: "daire",
    sehir: "İstanbul",
    ilce: "Kadıköy",
    mahalle: "Caferağa",
    metrekare: 95,
    odaSayisi: "2+1",
    beklenenKira: 45000,
    sozlesmeSuresi: 12,
    esyaliMi: false,
    status: "onaylandi",
    basvuruTarihi: "2026-05-15T11:03:00Z",
    atayan: "Burak Sezgin",
  },
  {
    id: "KG-2026-D7N4Q",
    adSoyad: "Hasan Aydın",
    telefon: "0533 445 67 89",
    eposta: "hasan.aydin@example.com",
    ikametSehir: "Ankara",
    mulkTipi: "mustakil",
    sehir: "Ankara",
    ilce: "Çankaya",
    mahalle: "Bahçelievler",
    metrekare: 220,
    odaSayisi: "4+1",
    beklenenKira: 65000,
    sozlesmeSuresi: 24,
    esyaliMi: false,
    status: "bekliyor",
    basvuruTarihi: "2026-05-17T14:21:00Z",
  },
  {
    id: "KG-2026-E1R8Y",
    adSoyad: "Fatma Yılmaz",
    telefon: "0507 666 22 11",
    eposta: "fatma.yilmaz@example.com",
    ikametSehir: "İzmir",
    mulkTipi: "daire",
    sehir: "İzmir",
    ilce: "Karşıyaka",
    mahalle: "Bostanlı",
    metrekare: 130,
    odaSayisi: "3+1",
    beklenenKira: 32000,
    sozlesmeSuresi: 12,
    esyaliMi: true,
    status: "degerleniyor",
    basvuruTarihi: "2026-05-16T09:55:00Z",
    atayan: "Merve Aydın",
  },
  {
    id: "KG-2026-F3T6Z",
    adSoyad: "Emre Çelik",
    telefon: "0544 333 99 88",
    eposta: "emre.celik@example.com",
    ikametSehir: "Adana",
    mulkTipi: "dukkan",
    sehir: "Adana",
    ilce: "Seyhan",
    mahalle: "Reşatbey",
    metrekare: 45,
    odaSayisi: "1+0",
    beklenenKira: 25000,
    sozlesmeSuresi: 36,
    esyaliMi: false,
    status: "reddedildi",
    basvuruTarihi: "2026-05-14T16:30:00Z",
    notlar: "Bölgede uygun kiracı bulunmadı, yetkimiz dışında.",
    atayan: "Burak Sezgin",
  },
  {
    id: "KG-2026-G9V2W",
    adSoyad: "Selin Korkmaz",
    telefon: "0531 222 11 99",
    eposta: "selin.k@example.com",
    ikametSehir: "Gaziantep",
    mulkTipi: "daire",
    sehir: "Gaziantep",
    ilce: "Şahinbey",
    mahalle: "Atatürk",
    metrekare: 105,
    odaSayisi: "2+1",
    beklenenKira: 19500,
    sozlesmeSuresi: 12,
    esyaliMi: false,
    status: "onaylandi",
    basvuruTarihi: "2026-05-13T12:00:00Z",
    atayan: "Selin Kara",
  },
  {
    id: "KG-2026-H4X7K",
    adSoyad: "Veli Aksoy",
    telefon: "0541 555 44 33",
    eposta: "veli.aksoy@example.com",
    ikametSehir: "Mersin",
    mulkTipi: "daire",
    sehir: "Mersin",
    ilce: "Yenişehir",
    mahalle: "Bahçe",
    metrekare: 90,
    odaSayisi: "2+1",
    beklenenKira: 16500,
    sozlesmeSuresi: 12,
    esyaliMi: false,
    status: "bekliyor",
    basvuruTarihi: "2026-05-17T16:45:00Z",
  },
  {
    id: "KG-2026-J5Y1L",
    adSoyad: "Zeynep Akar",
    telefon: "0535 999 88 77",
    eposta: "zeynep.a@example.com",
    ikametSehir: "İstanbul",
    mulkTipi: "daire",
    sehir: "İstanbul",
    ilce: "Beşiktaş",
    mahalle: "Levent",
    metrekare: 140,
    odaSayisi: "3+1",
    beklenenKira: 78000,
    sozlesmeSuresi: 12,
    esyaliMi: true,
    status: "degerleniyor",
    basvuruTarihi: "2026-05-15T18:30:00Z",
    atayan: "Selin Kara",
  },
  {
    id: "KG-2026-K2Z9M",
    adSoyad: "Burak Şahin",
    telefon: "0530 111 22 33",
    eposta: "burak.s@example.com",
    ikametSehir: "Yurt Dışında Yaşıyorum",
    mulkTipi: "mustakil",
    sehir: "Muğla",
    ilce: "Bodrum",
    mahalle: "Türkbükü",
    metrekare: 280,
    odaSayisi: "4+1",
    beklenenKira: 95000,
    sozlesmeSuresi: 24,
    esyaliMi: true,
    status: "onaylandi",
    basvuruTarihi: "2026-05-10T07:15:00Z",
    atayan: "Merve Aydın",
  },
  {
    id: "KG-2026-L8A3N",
    adSoyad: "Murat Polat",
    telefon: "0542 444 33 22",
    eposta: "m.polat@example.com",
    ikametSehir: "Ankara",
    mulkTipi: "daire",
    sehir: "Ankara",
    ilce: "Yenimahalle",
    mahalle: "Demetevler",
    metrekare: 80,
    odaSayisi: "2+1",
    beklenenKira: 13000,
    sozlesmeSuresi: 12,
    esyaliMi: false,
    status: "bekliyor",
    basvuruTarihi: "2026-05-17T20:10:00Z",
  },
  {
    id: "KG-2026-M6B4P",
    adSoyad: "Esra Korkmaz",
    telefon: "0539 777 66 55",
    eposta: "esra.k@example.com",
    ikametSehir: "İzmir",
    mulkTipi: "daire",
    sehir: "İzmir",
    ilce: "Bornova",
    mahalle: "Erzene",
    metrekare: 70,
    odaSayisi: "1+1",
    beklenenKira: 14500,
    sozlesmeSuresi: 12,
    esyaliMi: true,
    status: "reddedildi",
    basvuruTarihi: "2026-05-12T13:20:00Z",
    notlar: "Beklenen kira piyasanın çok altında.",
    atayan: "Burak Sezgin",
  },
];

export const STATUS_META: Record<
  ApplicationStatus,
  { label: string; color: string; bg: string; ring: string; dot: string }
> = {
  bekliyor: {
    label: "Bekliyor",
    color: "text-amber-700",
    bg: "bg-amber-50",
    ring: "ring-amber-200",
    dot: "bg-amber-500",
  },
  degerleniyor: {
    label: "Değerleniyor",
    color: "text-sky-700",
    bg: "bg-sky-50",
    ring: "ring-sky-200",
    dot: "bg-sky-500",
  },
  onaylandi: {
    label: "Onaylandı",
    color: "text-emerald-700",
    bg: "bg-emerald-50",
    ring: "ring-emerald-200",
    dot: "bg-emerald-500",
  },
  reddedildi: {
    label: "Reddedildi",
    color: "text-rose-700",
    bg: "bg-rose-50",
    ring: "ring-rose-200",
    dot: "bg-rose-500",
  },
};
